"""
Auto-generated SQLAlchemy models from database reflection.
Generated by: generate_models.py
"""

from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, Float, ForeignKey
from sqlalchemy.orm import relationship
from database import Base


class EventLocation(Base):
    __tablename__ = "event_location"

    user_id = Column(String(255), primary_key=True, nullable=False)
    location_id = Column(String(255), primary_key=True, nullable=False)
    news_id = Column(String(255), primary_key=True, nullable=False)
    event_type = Column(String(255))
    event_topic = Column(String(255))
    event_desc = Column(Text)
    trust_score = Column(Float)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    deleted_at = Column(DateTime)
    event_accept = Column(Boolean)


class UsersAuthLog(Base):
    __tablename__ = "users_auth_log"

    auth_log_id = Column(String(255), primary_key=True, nullable=False)
    user_id = Column(String(255))
    auth_status_id = Column(String(255))
    auth_log_time_created = Column(DateTime)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    deleted_at = Column(DateTime)


class User(Base):
    __tablename__ = "user"

    user_id = Column(String(255), primary_key=True, nullable=False)
    image_id = Column(String(255))
    username = Column(String(255))
    password = Column(String(255))
    user_firstname = Column(String(255))
    user_lastname = Column(String(255))
    user_nickname = Column(String(255))
    user_email = Column(String(255))
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    deleted_at = Column(DateTime)


class MapLocation(Base):
    __tablename__ = "map_location"

    location_id = Column(String(255), primary_key=True, nullable=False)
    priority = Column(String(255))
    lat = Column(Float)
    lng = Column(Float)
    type = Column(String(255))
    radius = Column(Integer)
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    deleted_at = Column(DateTime)


class NewsType(Base):
    __tablename__ = "news_type"

    news_type_id = Column(String(255), primary_key=True, nullable=False)


class News(Base):
    __tablename__ = "news"

    news_id = Column(String(255), primary_key=True, nullable=False)
    date_time = Column(String(255))
    keyword_location = Column(String(255))
    news_header = Column(Text)
    news_desc = Column(Text)
    news_source = Column(Text)
    hashtag = Column(String(255))
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    deleted_at = Column(DateTime)
    news_type_id = Column(String(255))
    embedding = Column(String)


class Images(Base):
    __tablename__ = "images"

    image_id = Column(String(255), primary_key=True, nullable=False)
    image_path = Column(String(255))
    created_at = Column(DateTime)
    updated_at = Column(DateTime)
    deleted_at = Column(DateTime)


class ImagesNews(Base):
    __tablename__ = "images_news"

    news_id = Column(String(255), primary_key=True, nullable=False)
    image_id = Column(String(255))
    order_no = Column(Integer)

